name: notes
description: Flutter Firebase And DDD Course - Notes
homepage: https://sadra.at
repository: https://github.com/xsadra/xDart
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dartz: "^0.9.0-dev.6"
  freezed_annotation: "^0.7.1"
  flutter_bloc: "^3.2.0"

dev_dependencies:
  build_runner:
  freezed: "^0.9.2"

flutter:
  uses-material-design: true
