name: dart_extension_methods
description: A sample command-line application.
version: 1.0.0
homepage: https://sadra.at

environment:
  sdk: '>=2.7.0 <3.0.0'

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
