name: sailor_navigation
description: Flutter Sailor Navigation Library
homepage: https://sadra.at
version: 1.0.0+1
repository: https://github.com/xsadra/xDart

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sailor: ^0.7.1

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
